site_name: Cupoch - Robotics with GPU computing

theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: true

nav:
  - 'Home' : index.md

markdown_extensions:
  - codehilite:
      linenums: true
      guess_lang: False